#spring:
#  application:
#    name: todo-app
#    datasource:
#      driver-class-name: org.h2.Driver
#      username: moha
#      password: mohammed
#      url: "jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE"
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: create-drop
spring:
  application:
    name: todo-app
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://blogs.cqeoaid8pv2d.eu-west-3.rds.amazonaws.com:3306/tareas
    username: root
    password: 123456789
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # Opciones: validate, update, create, create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: false
